// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIGEat7q2q0jL0fFZbaiKz1EIisyJ4laY',
    appId: '1:276981273207:web:d8284bf61ae48270b32c72',
    messagingSenderId: '276981273207',
    projectId: 'chat-app-1c2a2',
    authDomain: 'chat-app-1c2a2.firebaseapp.com',
    storageBucket: 'chat-app-1c2a2.appspot.com',
    measurementId: 'G-8YN54NDEWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDicQb7dPAuDtf1wzyP9XEi51T2vtA42fU',
    appId: '1:276981273207:android:bd117ac42a97fb23b32c72',
    messagingSenderId: '276981273207',
    projectId: 'chat-app-1c2a2',
    storageBucket: 'chat-app-1c2a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSHlwnBfCcKRRWIVPKtayWLCkrb-leUrg',
    appId: '1:276981273207:ios:47410706dbcc0856b32c72',
    messagingSenderId: '276981273207',
    projectId: 'chat-app-1c2a2',
    storageBucket: 'chat-app-1c2a2.appspot.com',
    iosClientId: '276981273207-8igkjlduc41qqkrmk6j447tusmg88em2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSHlwnBfCcKRRWIVPKtayWLCkrb-leUrg',
    appId: '1:276981273207:ios:47410706dbcc0856b32c72',
    messagingSenderId: '276981273207',
    projectId: 'chat-app-1c2a2',
    storageBucket: 'chat-app-1c2a2.appspot.com',
    iosClientId: '276981273207-8igkjlduc41qqkrmk6j447tusmg88em2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
